private _display = findDisplay 49;
private _ctrlContinueButton = _display displayCtrl 2;
private _ctrlBottomBar = _display displayCtrl 120;
private _ctrlAbortBtn = _display displayCtrl 104;
private _ctrlRespawnBtn = _display displayCtrl 103;
private _ctrlFieldMenuBtn = _display displayCtrl 122;
_ctrlAbortBtn ctrlEnable true;
_ctrlAbortBtn ctrlSetEventHandler["ButtonClick", "deleteVehicle Old_Vehicle_Spawned; call Vortex_fnc_saveGear; [] spawn Vortex_fnc_outro; (findDisplay 49) closeDisplay 2; true"];
_ctrlRespawnBtn ctrlEnable true;
_ctrlRespawnBtn ctrlSetEventHandler["ButtonClick", "call Vortex_fnc_respawner; (findDisplay 49) closeDisplay 2; true"];
_ctrlRespawnBtn ctrlSetText "Respawn";
_ctrlFieldMenuBtn ctrlEnable false;
_ctrlFieldMenuBtn ctrlShow false;
_ctrlContinueButton ctrlSetText "AP CQC";
_ctrlContinueButton ctrlRemoveAllEventHandlers "ButtonClick";
_ctrlBottomBar ctrlSetText "Developed by kny";
uiSleep 0.1;